name: Code Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync 
          uv add ruff
          uv add black
          uv add mypy
    
      - name: Run code linting check
        run: |
          uv run black --check .
          uv run ruff check .
          uv run mypy .
